-- Stock Symbol table
CREATE TABLE IF NOT EXISTS stock_symbol (
  symbol VARCHAR(10) PRIMARY KEY,
  name VARCHAR(255),
  exchange VARCHAR(255),
  exchange_short_name VARCHAR(255),
  type VARCHAR(255)
);
-- Daily Price table
CREATE TABLE IF NOT EXISTS daily_price (
  symbol VARCHAR(10),
  date DATE NOT NULL,
  open DECIMAL(10, 2),
  high DECIMAL(10, 2),
  low DECIMAL(10, 2),
  close DECIMAL(10, 2),
  adjusted_close DECIMAL(10, 2),
  volume BIGINT,
  PRIMARY KEY (symbol, date)
);
CREATE INDEX IF NOT EXISTS idx_daily_price_symbol_date ON daily_price(symbol, date);
-- Income Statement table
CREATE TABLE IF NOT EXISTS income_statement (
  symbol VARCHAR(10),
  date DATE NOT NULL,
  period VARCHAR(10) NOT NULL,
  calendar_year VARCHAR(4),
  reported_currency VARCHAR(3),
  revenue DECIMAL(15, 2),
  cost_of_revenue DECIMAL(15, 2),
  gross_profit DECIMAL(15, 2),
  gross_profit_ratio DECIMAL(10, 4),
  research_and_development_expenses DECIMAL(15, 2),
  general_and_administrative_expenses DECIMAL(15, 2),
  selling_and_marketing_expenses DECIMAL(15, 2),
  selling_general_and_administrative_expenses DECIMAL(15, 2),
  operating_expenses DECIMAL(15, 2),
  operating_income DECIMAL(15, 2),
  operating_income_ratio DECIMAL(10, 4),
  ebitda DECIMAL(15, 2),
  ebitda_ratio DECIMAL(10, 4),
  net_income DECIMAL(15, 2),
  net_income_ratio DECIMAL(10, 4),
  eps DECIMAL(10, 2),
  eps_diluted DECIMAL(10, 2),
  weighted_average_shares_outstanding DECIMAL(15, 0),
  weighted_average_shares_outstanding_diluted DECIMAL(15, 0),
  link VARCHAR(255),
  PRIMARY KEY (symbol, date, period)
);
CREATE INDEX IF NOT EXISTS idx_income_statement_symbol_date ON income_statement(symbol, date);
-- Balance Sheet table
CREATE TABLE IF NOT EXISTS balance_sheet (
  symbol VARCHAR(10),
  date DATE NOT NULL,
  period VARCHAR(10) NOT NULL,
  calendar_year VARCHAR(4),
  reported_currency VARCHAR(3),
  cash_and_cash_equivalents DECIMAL(15, 2),
  short_term_investments DECIMAL(15, 2),
  cash_and_short_term_investments DECIMAL(15, 2),
  net_receivables DECIMAL(15, 2),
  inventory DECIMAL(15, 2),
  total_current_assets DECIMAL(15, 2),
  property_plant_equipment_net DECIMAL(15, 2),
  goodwill DECIMAL(15, 2),
  intangible_assets DECIMAL(15, 2),
  long_term_investments DECIMAL(15, 2),
  total_non_current_assets DECIMAL(15, 2),
  total_assets DECIMAL(15, 2),
  accounts_payables DECIMAL(15, 2),
  short_term_debt DECIMAL(15, 2),
  total_current_liabilities DECIMAL(15, 2),
  long_term_debt DECIMAL(15, 2),
  total_non_current_liabilities DECIMAL(15, 2),
  total_liabilities DECIMAL(15, 2),
  total_stockholders_equity DECIMAL(15, 2),
  total_equity DECIMAL(15, 2),
  total_liabilities_and_stockholders_equity DECIMAL(15, 2),
  total_investments DECIMAL(15, 2),
  total_debt DECIMAL(15, 2),
  net_debt DECIMAL(15, 2),
  link VARCHAR(255),
  PRIMARY KEY (symbol, date, period)
);
CREATE INDEX IF NOT EXISTS idx_balance_sheet_symbol_date ON balance_sheet(symbol, date);
-- Cash Flow table
CREATE TABLE IF NOT EXISTS cash_flow (
  symbol VARCHAR(10),
  date DATE NOT NULL,
  period VARCHAR(10) NOT NULL,
  calendar_year VARCHAR(4),
  reported_currency VARCHAR(3),
  net_income DECIMAL(15, 2),
  depreciation_and_amortization DECIMAL(15, 2),
  stock_based_compensation DECIMAL(15, 2),
  change_in_working_capital DECIMAL(15, 2),
  accounts_receivables DECIMAL(15, 2),
  inventory DECIMAL(15, 2),
  accounts_payables DECIMAL(15, 2),
  net_cash_provided_by_operating_activities DECIMAL(15, 2),
  investments_in_property_plant_and_equipment DECIMAL(15, 2),
  acquisitions_net DECIMAL(15, 2),
  purchases_of_investments DECIMAL(15, 2),
  sales_maturities_of_investments DECIMAL(15, 2),
  net_cash_used_for_investing_activities DECIMAL(15, 2),
  debt_repayment DECIMAL(15, 2),
  common_stock_repurchased DECIMAL(15, 2),
  dividends_paid DECIMAL(15, 2),
  net_cash_used_provided_by_financing_activities DECIMAL(15, 2),
  net_change_in_cash DECIMAL(15, 2),
  operating_cash_flow DECIMAL(15, 2),
  capital_expenditure DECIMAL(15, 2),
  free_cash_flow DECIMAL(15, 2),
  link VARCHAR(255),
  PRIMARY KEY (symbol, date, period)
);
CREATE INDEX IF NOT EXISTS idx_cash_flow_symbol_date ON cash_flow(symbol, date);
-- Company Metrics table
CREATE TABLE IF NOT EXISTS metrics (
  symbol TEXT,
  date TEXT,
  calendar_year INTEGER,
  period TEXT,
  revenue_per_share REAL,
  net_income_per_share REAL,
  operating_cash_flow_per_share REAL,
  free_cash_flow_per_share REAL,
  cash_per_share REAL,
  book_value_per_share REAL,
  tangible_book_value_per_share REAL,
  shareholders_equity_per_share REAL,
  interest_debt_per_share REAL,
  debt_to_equity REAL,
  debt_to_assets REAL,
  net_debt_to_EBITDA REAL,
  current_ratio REAL,
  interest_coverage REAL,
  income_quality REAL,
  payout_ratio REAL,
  sga_to_revenue REAL,
  rnd_to_revenue REAL,
  intangibles_to_total_assets REAL,
  capex_to_operating_cash_flow REAL,
  capex_to_revenue REAL,
  capex_to_depreciation REAL,
  stock_based_compensation_to_revenue REAL,
  graham_number REAL,
  roic REAL,
  return_on_tangible_assets REAL,
  graham_net_net REAL,
  working_capital REAL,
  tangible_asset_value REAL,
  net_current_asset_value REAL,
  invested_capital REAL,
  days_sales_outstanding REAL,
  days_payables_outstanding REAL,
  days_inventory_onhand REAL,
  receivables_turnover REAL,
  payables_turnover REAL,
  inventory_turnover REAL,
  roe REAL,
  capex_per_share REAL,
  quick_ratio REAL,
  cash_ratio REAL,
  operating_cycle REAL,
  cash_conversion_cycle REAL,
  gross_profit_margin REAL,
  operating_profit_margin REAL,
  pretax_profit_margin REAL,
  net_profit_margin REAL,
  effective_tax_rate REAL,
  return_on_assets REAL,
  return_on_capital_employed REAL,
  net_income_per_ebt REAL,
  ebt_per_ebit REAL,
  ebit_per_revenue REAL,
  debt_ratio REAL,
  long_term_debt_to_capitalization REAL,
  total_debt_to_capitalization REAL,
  cash_flow_to_debt_ratio REAL,
  company_equity_multiplier REAL,
  fixed_asset_turnover REAL,
  asset_turnover REAL,
  operating_cash_flow_sales_ratio REAL,
  free_cash_flow_operating_cash_flow_ratio REAL,
  cash_flow_coverage_ratios REAL,
  short_term_coverage_ratios REAL,
  capital_expenditure_coverage_ratio REAL,
  dividend_paid_and_capex_coverage_ratio REAL,
  price_fair_value REAL,
  PRIMARY KEY (symbol, date)
);
CREATE INDEX IF NOT EXISTS idx_metrics_calendar_year_period ON metrics(symbol, calendar_year, period);
CREATE INDEX IF NOT EXISTS idx_metrics_symbol ON metrics(symbol);

CREATE TABLE IF NOT EXISTS owner_earnings (
  symbol VARCHAR(10) NOT NULL,
  date DATE NOT NULL,
  averagePPE DECIMAL(10, 5),
  maintenanceCapex BIGINT,
  ownersEarnings BIGINT,
  growthCapex BIGINT,
  ownersEarningsPerShare DECIMAL(10, 2),
  PRIMARY KEY (symbol, date)
);
CREATE INDEX IF NOT EXISTS idx_owner_earnings_symbol ON owner_earnings(symbol);