-- Stock Symbol table
CREATE TABLE IF NOT EXISTS stock_symbol (
  symbol VARCHAR(10) PRIMARY KEY,
  name VARCHAR(255),
  exchange VARCHAR(255),
  exchange_short_name VARCHAR(255),
  type VARCHAR(255),
  sector VARCHAR(255),
  industry VARCHAR(255)
);
-- Daily Price table
-- All prices are already adjusted, they are from
-- https://financialmodelingprep.com/stable/historical-price-eod/dividend-adjusted
CREATE TABLE IF NOT EXISTS daily_price (
  symbol VARCHAR(10),
  date DATE NOT NULL,
  open DECIMAL(10, 2),
  high DECIMAL(10, 2),
  low DECIMAL(10, 2),
  close DECIMAL(10, 2),
  volume BIGINT,
  PRIMARY KEY (symbol, date)
);
CREATE INDEX IF NOT EXISTS idx_daily_price_symbol_date ON daily_price(symbol, date);
-- Income Statement table
CREATE TABLE IF NOT EXISTS income_statement (
  symbol VARCHAR(10),
  date DATE NOT NULL,
  filing_date DATE,
  accepted_date TIMESTAMP,
  period VARCHAR(10) NOT NULL,
  fiscal_year VARCHAR(4),
  reported_currency VARCHAR(3),
  cik VARCHAR(10),
  revenue DECIMAL(15, 2),
  cost_of_revenue DECIMAL(15, 2),
  gross_profit DECIMAL(15, 2),
  research_and_development_expenses DECIMAL(15, 2),
  general_and_administrative_expenses DECIMAL(15, 2),
  selling_and_marketing_expenses DECIMAL(15, 2),
  selling_general_and_administrative_expenses DECIMAL(15, 2),
  other_expenses DECIMAL(15, 2),
  operating_expenses DECIMAL(15, 2),
  cost_and_expenses DECIMAL(15, 2),
  net_interest_income DECIMAL(15, 2),
  interest_income DECIMAL(15, 2),
  interest_expense DECIMAL(15, 2),
  depreciation_and_amortization DECIMAL(15, 2),
  ebitda DECIMAL(15, 2),
  ebit DECIMAL(15, 2),
  non_operating_income_excluding_interest DECIMAL(15, 2),
  operating_income DECIMAL(15, 2),
  total_other_income_expenses_net DECIMAL(15, 2),
  income_before_tax DECIMAL(15, 2),
  income_tax_expense DECIMAL(15, 2),
  net_income_from_continuing_operations DECIMAL(15, 2),
  net_income_from_discontinued_operations DECIMAL(15, 2),
  other_adjustments_to_net_income DECIMAL(15, 2),
  net_income DECIMAL(15, 2),
  net_income_deductions DECIMAL(15, 2),
  bottom_line_net_income DECIMAL(15, 2),
  eps DECIMAL(10, 2),
  eps_diluted DECIMAL(10, 2),
  weighted_average_shares_outstanding DECIMAL(15, 0),
  weighted_average_shares_outstanding_diluted DECIMAL(15, 0),
  PRIMARY KEY (symbol, date, period)
);
CREATE INDEX IF NOT EXISTS idx_income_statement_symbol_date ON income_statement(symbol, date);
-- Balance Sheet table
CREATE TABLE IF NOT EXISTS balance_sheet (
  symbol VARCHAR(10),
  date DATE NOT NULL,
  filing_date DATE,  
  accepted_date TIMESTAMP,
  period VARCHAR(10) NOT NULL,
  fiscal_year VARCHAR(4),
  reported_currency VARCHAR(3),
  cik VARCHAR(10),
  cash_and_cash_equivalents DECIMAL(15, 2),
  short_term_investments DECIMAL(15, 2),
  cash_and_short_term_investments DECIMAL(15, 2),
  net_receivables DECIMAL(15, 2),
  accounts_receivables DECIMAL(15, 2),
  other_receivables DECIMAL(15, 2),
  inventory DECIMAL(15, 2),
  prepaids DECIMAL(15, 2),
  other_current_assets DECIMAL(15, 2),
  total_current_assets DECIMAL(15, 2),
  property_plant_equipment_net DECIMAL(15, 2),
  goodwill DECIMAL(15, 2),
  intangible_assets DECIMAL(15, 2),
  goodwill_and_intangible_assets DECIMAL(15, 2),
  long_term_investments DECIMAL(15, 2),
  tax_assets DECIMAL(15, 2),
  other_non_current_assets DECIMAL(15, 2),
  total_non_current_assets DECIMAL(15, 2),
  other_assets DECIMAL(15, 2),
  total_assets DECIMAL(15, 2),
  total_payables DECIMAL(15, 2),
  account_payables DECIMAL(15, 2),
  other_payables DECIMAL(15, 2),
  accrued_expenses DECIMAL(15, 2),
  short_term_debt DECIMAL(15, 2),
  capital_lease_obligations_current DECIMAL(15, 2),
  tax_payables DECIMAL(15, 2),
  deferred_revenue DECIMAL(15, 2),
  other_current_liabilities DECIMAL(15, 2),
  total_current_liabilities DECIMAL(15, 2),
  long_term_debt DECIMAL(15, 2),
  capital_lease_obligations_non_current DECIMAL(15, 2),
  deferred_revenue_non_current DECIMAL(15, 2),
  deferred_tax_liabilities_non_current DECIMAL(15, 2),
  other_non_current_liabilities DECIMAL(15, 2),
  total_non_current_liabilities DECIMAL(15, 2),
  other_liabilities DECIMAL(15, 2),
  capital_lease_obligations DECIMAL(15, 2),
  total_liabilities DECIMAL(15, 2),
  treasury_stock DECIMAL(15, 2),
  preferred_stock DECIMAL(15, 2),
  common_stock DECIMAL(15, 2),
  retained_earnings DECIMAL(15, 2),
  additional_paid_in_capital DECIMAL(15, 2),
  accumulated_other_comprehensive_income_loss DECIMAL(15, 2),
  other_total_stockholders_equity DECIMAL(15, 2),
  total_stockholders_equity DECIMAL(15, 2),
  total_equity DECIMAL(15, 2),
  minority_interest DECIMAL(15, 2),
  total_liabilities_and_total_equity DECIMAL(15, 2),
  total_investments DECIMAL(15, 2),
  total_debt DECIMAL(15, 2),
  net_debt DECIMAL(15, 2),
  PRIMARY KEY (symbol, date, period)
);
CREATE INDEX IF NOT EXISTS idx_balance_sheet_symbol_date ON balance_sheet(symbol, date);
-- Cash Flow table
CREATE TABLE IF NOT EXISTS cash_flow (
  symbol VARCHAR(10),
  date DATE NOT NULL,
  filing_date DATE,
  accepted_date TIMESTAMP,
  period VARCHAR(10) NOT NULL,
  fiscal_year VARCHAR(4),
  reported_currency VARCHAR(3),
  cik VARCHAR(10),
  net_income DECIMAL(15, 2),
  depreciation_and_amortization DECIMAL(15, 2),
  deferred_income_tax DECIMAL(15, 2),
  stock_based_compensation DECIMAL(15, 2),
  change_in_working_capital DECIMAL(15, 2),
  accounts_receivables DECIMAL(15, 2),
  inventory DECIMAL(15, 2),
  accounts_payables DECIMAL(15, 2),
  other_working_capital DECIMAL(15, 2),
  other_non_cash_items DECIMAL(15, 2),
  net_cash_provided_by_operating_activities DECIMAL(15, 2),
  investments_in_property_plant_and_equipment DECIMAL(15, 2),
  acquisitions_net DECIMAL(15, 2),
  purchases_of_investments DECIMAL(15, 2),
  sales_maturities_of_investments DECIMAL(15, 2),
  other_investing_activities DECIMAL(15, 2),
  net_cash_provided_by_investing_activities DECIMAL(15, 2),
  net_debt_issuance DECIMAL(15, 2),
  long_term_net_debt_issuance DECIMAL(15, 2),
  short_term_net_debt_issuance DECIMAL(15, 2),
  net_stock_issuance DECIMAL(15, 2),
  net_common_stock_issuance DECIMAL(15, 2),
  common_stock_issuance DECIMAL(15, 2),
  common_stock_repurchased DECIMAL(15, 2),
  net_preferred_stock_issuance DECIMAL(15, 2),
  net_dividends_paid DECIMAL(15, 2),
  common_dividends_paid DECIMAL(15, 2),
  preferred_dividends_paid DECIMAL(15, 2),
  other_financing_activities DECIMAL(15, 2),
  net_cash_provided_by_financing_activities DECIMAL(15, 2),
  effect_of_forex_changes_on_cash DECIMAL(15, 2),
  net_change_in_cash DECIMAL(15, 2),
  cash_at_end_of_period DECIMAL(15, 2),
  cash_at_beginning_of_period DECIMAL(15, 2),
  operating_cash_flow DECIMAL(15, 2),
  capital_expenditure DECIMAL(15, 2),
  free_cash_flow DECIMAL(15, 2),
  income_taxes_paid DECIMAL(15, 2),
  interest_paid DECIMAL(15, 2),
  PRIMARY KEY (symbol, date, period)
);
CREATE INDEX IF NOT EXISTS idx_cash_flow_symbol_date ON cash_flow(symbol, date);

-- Company Metrics table
CREATE TABLE IF NOT EXISTS metrics (
  symbol VARCHAR(10),
  date DATE NOT NULL,
  fiscal_year VARCHAR(4),
  period VARCHAR(10),
  reported_currency VARCHAR(3),
  gross_profit_margin REAL,
  ebitda_margin REAL,
  ebit_margin REAL,
  operating_profit_margin REAL,
  pretax_profit_margin REAL,
  net_profit_margin REAL,
  continuous_operations_profit_margin REAL,
  bottom_line_profit_margin REAL,
  receivables_turnover REAL,
  payables_turnover REAL,
  inventory_turnover REAL,
  fixed_asset_turnover REAL,
  asset_turnover REAL,
  working_capital_turnover_ratio REAL,
  current_ratio REAL,
  quick_ratio REAL,
  cash_ratio REAL,
  solvency_ratio REAL,
  price_to_earnings_ratio REAL,
  price_to_earnings_growth_ratio REAL,
  forward_price_to_earnings_growth_ratio REAL,
  price_to_book_ratio REAL,
  price_to_sales_ratio REAL,
  price_to_free_cash_flow_ratio REAL,
  price_to_operating_cash_flow_ratio REAL,
  price_to_fair_value REAL,
  enterprise_value_multiple REAL,
  ev_to_sales REAL,
  ev_to_operating_cash_flow REAL,
  ev_to_free_cash_flow REAL,
  ev_to_ebitda REAL,
  debt_to_assets_ratio REAL,
  debt_to_equity_ratio REAL,
  debt_to_capital_ratio REAL,
  long_term_debt_to_capital_ratio REAL,
  financial_leverage_ratio REAL,
  debt_to_market_cap REAL,
  net_debt_to_ebitda REAL,
  operating_cash_flow_ratio REAL,
  operating_cash_flow_sales_ratio REAL,
  free_cash_flow_operating_cash_flow_ratio REAL,
  debt_service_coverage_ratio REAL,
  interest_coverage_ratio REAL,
  short_term_operating_cash_flow_coverage_ratio REAL,
  operating_cash_flow_coverage_ratio REAL,
  capital_expenditure_coverage_ratio REAL,
  dividend_paid_and_capex_coverage_ratio REAL,
  dividend_payout_ratio REAL,
  dividend_yield REAL,
  dividend_yield_percentage REAL,
  dividend_per_share REAL,
  revenue_per_share REAL,
  net_income_per_share REAL,
  interest_debt_per_share REAL,
  cash_per_share REAL,
  book_value_per_share REAL,
  tangible_book_value_per_share REAL,
  shareholders_equity_per_share REAL,
  operating_cash_flow_per_share REAL,
  capex_per_share REAL,
  free_cash_flow_per_share REAL,
  net_income_per_ebt REAL,
  ebt_per_ebit REAL,
  effective_tax_rate REAL,
  income_quality REAL,
  return_on_assets REAL,
  operating_return_on_assets REAL,
  return_on_equity REAL,
  return_on_invested_capital REAL,
  return_on_tangible_assets REAL,
  return_on_capital_employed REAL,
  earnings_yield REAL,
  free_cash_flow_yield REAL,
  tax_burden REAL,
  interest_burden REAL,
  working_capital REAL,
  invested_capital REAL,
  tangible_asset_value REAL,
  net_current_asset_value REAL,
  graham_number REAL,
  graham_net_net REAL,
  days_sales_outstanding REAL,
  days_payables_outstanding REAL,
  days_of_inventory_outstanding REAL,
  operating_cycle REAL,
  cash_conversion_cycle REAL,
  sga_to_revenue REAL,
  stock_based_compensation_to_revenue REAL,
  research_and_developement_to_revenue REAL,
  capex_to_revenue REAL,
  intangibles_to_total_assets REAL,
  capex_to_operating_cash_flow REAL,
  capex_to_depreciation REAL,
  sales_general_and_administrative_to_revenue REAL,
  market_cap REAL,
  enterprise_value REAL,
  average_receivables REAL,
  average_payables REAL,
  average_inventory REAL,
  free_cash_flow_to_equity REAL,
  free_cash_flow_to_firm REAL,
  filing_date DATE,  
  PRIMARY KEY (symbol, date)
);
CREATE INDEX IF NOT EXISTS idx_metrics_symbol ON metrics(symbol);

-- Suspicious Symbols table
CREATE TABLE IF NOT EXISTS suspicious_symbols (
    symbol VARCHAR(10) PRIMARY KEY,
    reason TEXT,
    bad_type TEXT CHECK( bad_type IN ('PRICE_HOLE') ) NOT NULL,
    date_added DATE DEFAULT (DATE('now'))
);

-- Price history from EODHD
CREATE TABLE IF NOT EXISTS daily_price_eodhd (
  symbol VARCHAR(10),
  date DATE NOT NULL,
  open DECIMAL(10, 2),
  high DECIMAL(10, 2),
  low DECIMAL(10, 2),
  close DECIMAL(10, 2),
  adjusted_close DECIMAL(10, 2),
  volume BIGINT,
  PRIMARY KEY (symbol, date)
);

-- Insider trading
CREATE TABLE IF NOT EXISTS insider_trading (
  symbol VARCHAR(10),
  filingDate DATE NOT NULL,
  transactionDate DATE NOT NULL,
  reportingCik VARCHAR(10),
  companyCik VARCHAR(10),
  transactionType VARCHAR(20),
  securitiesOwned BIGINT,
  reportingName VARCHAR(100),
  typeOfOwner VARCHAR(200),
  acquisitionOrDisposition VARCHAR(1),
  formType VARCHAR(1),
  directOrIndirect VARCHAR(1),
  securitiesTransacted BIGINT,
  price DECIMAL(10, 2),
  securityName VARCHAR(200),
  PRIMARY KEY (symbol, filingDate)
);
